https://www.multichannelsystems.com/sites/multichannelsystems.com/files/documents/data_sheets/MCS_24W700_100F-288_Layout.pdf

In [3]:
import pandas as pd

#mount Google Drive to access files
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Data/2.csv'
import os.path

#Double-Check that file can be opened and found by notebook
if os.path.isfile(file_path):
   print("File exists.")
else:
   print("File does not exist.")

Mounted at /content/drive
File does not exist.


In [6]:
# specify your path
file_path = '/2.csv'

# read the csv file
data = pd.read_csv(file_path)

print(data)

     Channel ID  Channel Label  Well ID Well Label Compound ID  Compound Name  \
0             4             21        0         A1       WT.NM            NaN   
1             6             31        0         A1       WT.NM            NaN   
2             2             12        0         A1       WT.NM            NaN   
3             5             22        0         A1       WT.NM            NaN   
4             7             32        0         A1       WT.NM            NaN   
..          ...            ...      ...        ...         ...            ...   
139         132             23       11         B6       WT.NM            NaN   
140         140             33       11         B6       WT.NM            NaN   
141         143             43       11         B6       WT.NM            NaN   
142         133             24       11         B6       WT.NM            NaN   
143         142             34       11         B6       WT.NM            NaN   

                 Experiment

In [8]:
import numpy as np

# Initialize a dictionary to hold the channel matrices for each well
well_matrices = {}

# Assign channel labels to the correct positions in the matrix
# Now, channel_positions dictionary keys are integers, not strings
channel_positions = {
    21: (0, 1),
    31: (0, 2),
    12: (1, 0),
    22: (1, 1),
    32: (1, 2),
    42: (1, 3),
    13: (2, 0),
    23: (2, 1),
    33: (2, 2),
    43: (2, 3),
    24: (3, 1),
    34: (3, 2)
}

# Go through each well
for well in data['Well Label'].unique():
    # Get the data for this well
    well_data = data[data['Well Label'] == well]
    
    # Create the empty 4x4 matrix
    channel_matrix = np.empty((4, 4), dtype=object)
    
    # Go through each channel in the well data
    for channel_label in channel_positions:
        # If the channel label is in the well data, store it in the correct position
        if channel_label in well_data['Channel Label'].unique():
            channel_matrix[channel_positions[channel_label]] = channel_label
            
    # Store the channel matrix in the well_matrices dictionary
    well_matrices[well] = channel_matrix


for well_label, channel_matrix in well_matrices.items():
    print(f"Well Label: {well_label}")
    print("Channel Matrix:")
    print(channel_matrix)
    print("\n")


Well Label: A1
Channel Matrix:
[[None 21 31 None]
 [12 22 32 42]
 [13 23 33 43]
 [None 24 34 None]]


Well Label: A2
Channel Matrix:
[[None 21 31 None]
 [12 22 32 42]
 [13 23 33 43]
 [None 24 34 None]]


Well Label: A3
Channel Matrix:
[[None 21 31 None]
 [12 22 32 42]
 [13 23 33 43]
 [None 24 34 None]]


Well Label: A4
Channel Matrix:
[[None 21 31 None]
 [12 22 32 42]
 [13 23 33 43]
 [None 24 34 None]]


Well Label: A5
Channel Matrix:
[[None 21 31 None]
 [12 22 32 42]
 [13 23 33 43]
 [None 24 34 None]]


Well Label: A6
Channel Matrix:
[[None 21 31 None]
 [12 22 32 42]
 [13 23 33 43]
 [None 24 34 None]]


Well Label: B1
Channel Matrix:
[[None 21 31 None]
 [12 22 32 42]
 [13 23 33 43]
 [None 24 34 None]]


Well Label: B2
Channel Matrix:
[[None 21 31 None]
 [12 22 32 42]
 [13 23 33 43]
 [None 24 34 None]]


Well Label: B3
Channel Matrix:
[[None 21 31 None]
 [12 22 32 42]
 [13 23 33 43]
 [None 24 34 None]]


Well Label: B4
Channel Matrix:
[[None 21 31 None]
 [12 22 32 42]
 [13 23 33 43]
 [

In [10]:
print("Unique Well Labels:", data['Well Label'].unique())
print("Unique Channel Labels:", data['Channel Label'].unique())


Unique Well Labels: ['A1' 'A2' 'A3' 'A4' 'A5' 'A6' 'B1' 'B2' 'B3' 'B4' 'B5' 'B6']
Unique Channel Labels: [21 31 12 22 32 42 13 23 33 43 24 34]


In [19]:
def visualize_spike_data(well_label):
    well_data = data[data['Well Label'] == well_label]
    
    # Create empty matrices for spike count and spike rate
    spike_count_matrix = [[None]*4 for _ in range(4)]
    spike_rate_matrix = [[None]*4 for _ in range(4)]
    
    # Iterate through each row in well data
    for i, row in well_data.iterrows():
        channel_label = str(row['Channel Label'])
        
        # Convert the channel label to matrix indices
        row_idx = int(channel_label[0]) - 1
        col_idx = int(channel_label[1]) - 1
        
        # Fill the matrices
        spike_count_matrix[row_idx][col_idx] = row['Spike Count']
        spike_rate_matrix[row_idx][col_idx] = row['Spike Rate [Hz]']
        
    print('Well Label:', well_label)
    print('Spike Count Matrix:')
    for row in spike_count_matrix:
        print(row)
        
    print('Spike Rate Matrix:')
    for row in spike_rate_matrix:
        print(row)

# Test the function with 'A1' well label
visualize_spike_data('A1')


Well Label: A1
Spike Count Matrix:
[None, 18, 10, None]
[9, 11, 8, 9]
[11, 14, 382, 21]
[None, 11, 387, None]
Spike Rate Matrix:
[None, 0.03, 0.017, None]
[0.015, 0.018, 0.013, 0.015]
[0.018, 0.023, 0.637, 0.035]
[None, 0.018, 0.645, None]


In [21]:
def visualize_spike_data(well_label):
    well_data = data[data['Well Label'] == well_label]
    
    # Create empty matrices for spike count and spike rate
    spike_count_matrix = [[None]*4 for _ in range(4)]
    spike_rate_matrix = [[None]*4 for _ in range(4)]
    
    # Iterate through each row in well data
    for i, row in well_data.iterrows():
        channel_label = str(row['Channel Label'])
        
        # Convert the channel label to matrix indices
        row_idx = int(channel_label[0]) - 1
        col_idx = int(channel_label[1]) - 1
        
        # Fill the matrices
        spike_count_matrix[row_idx][col_idx] = row['Spike Count']
        spike_rate_matrix[row_idx][col_idx] = row['Spike Rate [Hz]']
        
    # Transpose the matrices
    spike_count_matrix_transposed = list(map(list, zip(*spike_count_matrix)))
    spike_rate_matrix_transposed = list(map(list, zip(*spike_rate_matrix)))

    print('Well Label:', well_label)
    print('Transposed Spike Count Matrix:')
    for row in spike_count_matrix_transposed:
        print(row)
        
    print('Transposed Spike Rate Matrix:')
    for row in spike_rate_matrix_transposed:
        print(row)

# Test the function with 'A1' well label
visualize_spike_data('A1')


Well Label: A1
Transposed Spike Count Matrix:
[None, 9, 11, None]
[18, 11, 14, 11]
[10, 8, 382, 387]
[None, 9, 21, None]
Transposed Spike Rate Matrix:
[None, 0.015, 0.018, None]
[0.03, 0.018, 0.023, 0.018]
[0.017, 0.013, 0.637, 0.645]
[None, 0.015, 0.035, None]
